# Generated by Django 3.1.12 on 2024-12-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AquaticClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axie_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('stage', models.IntegerField()),
                ('current_price_usd', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BeastClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axie_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('stage', models.IntegerField()),
                ('current_price_usd', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BirdClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axie_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('stage', models.IntegerField()),
                ('current_price_usd', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BugClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axie_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('stage', models.IntegerField()),
                ('current_price_usd', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DawnClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axie_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('stage', models.IntegerField()),
                ('current_price_usd', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DuskClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axie_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('stage', models.IntegerField()),
                ('current_price_usd', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MechClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axie_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('stage', models.IntegerField()),
                ('current_price_usd', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlantClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axie_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('stage', models.IntegerField()),
                ('current_price_usd', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReptileClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axie_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('stage', models.IntegerField()),
                ('current_price_usd', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
